help:
	@IFS=$$'\n' ; \
        help_lines=(`fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//'`); \
        for help_line in $${help_lines[@]}; do \
            IFS=$$'#' ; \
            help_split=($$help_line) ; \
            help_command=`echo $${help_split[0]} | sed -e 's/^ *//' -e 's/ *$$//'` ; \
            help_info=`echo $${help_split[2]} | sed -e 's/^ *//' -e 's/ *$$//'` ; \
            printf "%-15s %s\n" $$help_command $$help_info ; \
        done


cart: ## Setup cart Componenet
	@ bash components/cart.sh

catalogue: ## Setup catalogue Component
	@bash components/catalogue.sh

mongodb: ## Setup mongodb Component
	@bash components/mongodb.sh

shell: ## Setup shell Component
	@bash components/shell.sh